/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlxd.ui;

import com.kvlxd.dao.KeDAO;
import com.kvlxd.dao.KeHangDAO;
import com.kvlxd.dao.KhoDAO;
import com.kvlxd.dao.LoaiHangDAO;
import com.kvlxd.dao.MatHangDAO;
import com.kvlxd.entity.KeHang;
import com.kvlxd.entity.Kho;
import com.kvlxd.entity.LoaiHang;
import com.kvlxd.entity.MatHang;
import com.kvlxd.util.Auth;
import com.kvlxd.util.MsgBox;
import com.kvlxd.util.XDate;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cuong
 */
public class MatHangJDialog extends javax.swing.JInternalFrame {

    /**
     * Creates new form MatHangJDialog
     */
    public MatHangJDialog() {
        initComponents();
        inits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        txtTenMatHang = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        cbbDonVi = new javax.swing.JComboBox<>();
        txtSL = new javax.swing.JTextField();
        txtHang = new javax.swing.JTextField();
        txtNgaySX = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSLHong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbbKe = new javax.swing.JComboBox<>();
        txtTenLoaiHang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbbKho = new javax.swing.JComboBox<>();

        jLabel2.setText("Mã MH");

        jLabel3.setText("Tên mặt hàng");

        jLabel4.setText("Đơn giá");

        jLabel5.setText("Đơn vị");

        jLabel6.setText("Tên loại hàng");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Hãng");

        jLabel9.setText("Ngày sản xuất");

        txtTenMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMatHangActionPerformed(evt);
            }
        });

        cbbDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel11.setText("SL hỏng");

        jLabel12.setText("Kệ");

        cbbKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTenLoaiHang.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbKe, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNgaySX)
                                .addComponent(txtMaMH)
                                .addComponent(txtTenMatHang)
                                .addComponent(txtDonGia)
                                .addComponent(cbbDonVi, 0, 354, Short.MAX_VALUE)
                                .addComponent(txtSL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSLHong, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtHang)
                                .addComponent(txtTenLoaiHang)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(txtTenMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(cbbDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtTenLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cbbKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSLHong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addContainerGap())
        );

        tabs.addTab("Thông tin chi tiết", jPanel1);

        jLabel10.setText("Tìm kiếm theo tên mặt hàng");

        tblMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã MH", "Tên mặt hàng", "Mã LH", "Đơn giá", "Đơn vị", "Số lượng", "Hãng", "Ngày sản xuất", "Kệ", "SL hỏng"
            }
        ));
        tblMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMatHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách mặt hàng", jPanel2);

        jLabel1.setText("Kho");

        cbbKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbKho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(cbbKho, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMatHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMatHangActionPerformed

    private void cbbKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhoItemStateChanged
        // TODO add your handling code here:
        this.fillTable();
        this.loadCbbKe();
        
    }//GEN-LAST:event_cbbKhoItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insertForm();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.updateForm();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.deleteForm();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatHangMouseClicked
        row = tblMatHang.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tblMatHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDonVi;
    private javax.swing.JComboBox<String> cbbKe;
    private javax.swing.JComboBox<String> cbbKho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblMatHang;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtNgaySX;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtSLHong;
    private javax.swing.JTextField txtTenLoaiHang;
    private javax.swing.JTextField txtTenMatHang;
    // End of variables declaration//GEN-END:variables
    int row = 0;
    MatHangDAO dao = new MatHangDAO();
    LoaiHangDAO lhdao = new LoaiHangDAO();
    KeHangDAO kdao = new KeHangDAO();
    KhoDAO khodao = new KhoDAO();

    private void inits() {
        loadCbbKho();
        loadCbbDV();
        loadCbbKe();
        fillTable();
        row = -1;
        updateStatus();
    }

    private void clearForm() {
        txtMaMH.setText("");
        txtTenMatHang.setText("");
        txtDonGia.setText("");
        txtHang.setText("");
        txtNgaySX.setText("");
        txtSL.setText("");
        txtSLHong.setText("");
        cbbKe.setSelectedIndex(0);
        cbbDonVi.setSelectedIndex(0);
        this.row = -1;
        updateStatus();
    }

    private void updateForm() {
        MatHang mh = getForm();
        try {
            dao.update(mh);
            fillTable();
            clearForm();
            tabs.setSelectedIndex(1);
            MsgBox.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Cập nhập thất bại");
        }
    }

    private void insertForm() {
        MatHang mh = getForm();
        try {
            dao.insert(mh);
            fillTable();
            clearForm();
            MsgBox.alert(this, "Thêm thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm thất bại");
        }
    }

    private void deleteForm() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyển xóa");
        } else {
            String mamh = txtMaMH.getText();
            if (MsgBox.confirm(this, "Bạn có muốn xóa mặt hàng này ")) {
                try {
                    dao.delete(mamh);
                    fillTable();
                    clearForm();
                    MsgBox.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại");
                    e.printStackTrace();
                }
            }
        }
    }

    MatHang getForm() {
        MatHang mh = new MatHang();
        mh.setMaMH(txtMaMH.getText());
        mh.setMaLH(txtTenLoaiHang.getText());
        KeHang k = (KeHang) cbbKe.getSelectedItem();
        mh.setMaKe(k.getMaKe());
        mh.setDonGia(Double.parseDouble(txtDonGia.getText()));
        mh.setDonVi(String.valueOf(cbbDonVi.getSelectedItem()));
        mh.setTenMH(txtTenMatHang.getText());
        mh.setSLHong(Double.parseDouble(txtSLHong.getText()));
        mh.setNgaySanXuat(new java.sql.Date(XDate.toDate(txtNgaySX.getText(), "yyyy-MM-dd").getTime()));
        mh.setHang(txtHang.getText());
        return mh;
    }

    void setForm(MatHang mh) {
        txtMaMH.setText(mh.getMaMH());
        txtTenMatHang.setText(mh.getTenMH());
        txtDonGia.setText(String.valueOf(mh.getDonGia()));
        cbbDonVi.setSelectedItem(mh.getDonVi());
        
            LoaiHang lh = lhdao.selectById(mh.getMaLH());
            txtTenLoaiHang.setText(lh.getTenLH());
        
        cbbKe.setSelectedItem(mh.getMaKe());
        txtSL.setText(String.valueOf(mh.getSoLuong()));
        txtSLHong.setText(String.valueOf(mh.getSLHong()));
        txtHang.setText(mh.getHang());
        txtNgaySX.setText(String.valueOf(mh.getNgaySanXuat()));
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblMatHang.getRowCount() - 1);
        //Trạng thái form
        txtMaMH.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //Trạng thái điều hướng
//        btnFirst.setEnabled(edit && !first);
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnLast.setEnabled(edit && !last);

    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);
        try {
            Kho kh = new Kho();
            if (cbbKho.getItemCount() != 0) {
                if (cbbKho.getSelectedIndex() != -1) {
                    kh = (Kho) cbbKho.getSelectedItem();
                } else {
                    return;
                }
            } else {
                return;
            }
            List<MatHang> list = dao.selectByMaKho(kh.getMaKho());
            if (list != null) {
                for (MatHang mh : list) {
                    model.addRow(new Object[]{mh.getMaMH(), mh.getTenMH(), mh.getMaLH(), mh.getDonGia(), mh.getDonVi(), mh.getSoLuong(), mh.getHang(), mh.getNgaySanXuat(), mh.getMaKe(), mh.getSLHong()});
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "lỗi truy vấn dữ liệu");
        }
    }

    private void prev() {
        if (row > 0) {
            row--;
            edit();
        }
    }

    private void first() {
        if (row != 0) {
            row = 0;
            edit();
        }
    }

    private void last() {
        row = tblMatHang.getRowCount() - 1;
        edit();
    }

    private void next() {
        row++;
        edit();
    }

    private void edit() {
        try {
            String mamh = String.valueOf(tblMatHang.getValueAt(row, 0));
            MatHang mh = dao.selectById(mamh);
            setForm(mh);
            tabs.setSelectedIndex(0);
            updateStatus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadCbbKho() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbKho.getModel();
        model.removeAllElements();
        List<Kho> list = khodao.selectAll();
        for (Kho k : list) {
            model.addElement(k);
        }
    }

    private void loadCbbDV() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbDonVi.getModel();
        model.removeAllElements();
        String[] dv = {"m3", "viên", "cái", "cây", "KG"};
        model.addElement("m3");
        model.addElement("viên");
        model.addElement("cái");
        model.addElement("cây");
        model.addElement("KG");
    }

    private void loadCbbKe() {
        Kho k1 = new Kho();
        if (cbbKho.getItemCount() != 0) {
            if (cbbKho.getSelectedIndex() != -1) {
                k1 = (Kho) cbbKho.getSelectedItem();
            } else {
                return;
            }
        } else {
            return;
        }
        String malh = lhdao.selectByMaKho(k1.getMaKho()).getTenLH();
        txtTenLoaiHang.setText(malh);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbKe.getModel();
        model.removeAllElements();
        List<KeHang> list = kdao.selectByMaKho(k1.getMaKho());
        for (KeHang ke : list) {
            model.addElement(ke);
        }
    }
}
